# Generated by Django 4.2.13 on 2024-07-12 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('initial_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_date', models.DateTimeField(auto_now_add=True)),
                ('returned_quantity', models.PositiveIntegerField()),
                ('all_items_returned', models.BooleanField(default=False)),
                ('returned_by', models.CharField(max_length=100)),
                ('comment_more', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='RestockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initial_value', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_more', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.PositiveIntegerField()),
                ('issued_to', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Field', 'Field'), ('Security', 'Security'), ('Unused', 'Unused'), ('Routine destination', 'Routine destination'), ('Will be return back', 'Will be return back')], max_length=30)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('is_returned', models.BooleanField(default=False)),
                ('comment_more', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
    ]
